### ISSUE TITLE
example request: how to get transaction id from processed transaction?

### ISSUE THREAD

**Issue by pitersky** [bitshares/bitsharesjs#9]
With the following example how do I get transaction hash of transaction returned from 'get_transaction' call?
```
import {Apis} from "bitsharesjs-ws";
import {ChainStore, FetchChain, PrivateKey, TransactionHelper, Aes, TransactionBuilder} from "bitsharesjs";

Apis.instance("wss://node.testnet.bitshares.eu/", true)
    .init_promise.then((res) => {
        console.log("connected to:", res[0].network_name, "network")

        return Apis.instance().db_api().exec( "get_transaction", [103,0] )
    }).then((res) => {
        // how do I get transaction hash here?
        console.log(res)
    });
```

**Comment by abitmore** [comment]
Answer: https://github.com/bitshares/bitshares-core/issues/587

**Comment by hkadim** [comment]
test

**Comment by hkadim** [comment]
using Javascript and nodejs
I used the get_transaction_hex to workaround a bug in types bitsharesjs.

```
var bitsharesjs = require("bitsharesjs/dist");
var bitsharesjsws = require("bitsharesjs-ws");
var Apis = bitsharesjsws.Apis;
var FetchChain = bitsharesjs.FetchChain;
var ChainStore = bitsharesjs.ChainStore;
var hash = bitsharesjs.hash;
var ops = bitsharesjs.ops;
Apis.instance().connect("wss://bitshares.openledger.info/ws");
Apis.instance().init_promise.then(function () {
  ChainStore.init().then(function () {
    Apis.instance().db_api().exec("get_transaction", [25074326, 0]).then((trans1) => {
      Apis.instance().db_api().exec("get_transaction_hex", [trans1]).then((trans) => { 

        var trx2 = ops.transaction.fromHex(trans);
        var buf2 = ops.transaction.toBuffer(trx2)

        var id = hash.sha256(buf2).toString('hex').substring(0, 40);
        console.log('Transaction ID :', id);        
      });
    });
  });
});`

**Comment by abitmore** [comment]
@hkadim what's the issue? `trx2` should be same to `trans1` excluded the `signatures` field.

**Comment by hkadim** [comment]
`using node v8.9.3 (npm v5.5.1)`
believe me they are not equel
```
this is the expirationfrom trans1:
"expiration":"2018-03-09T10:29:00"

and this ist expiration from trx2:
"expiration":1520591340
```

 at first I used the 
`ops.transaction.fromObject(trans1)` 
 without the get_transaction_hex
and the problem was the "expiration":"2018-03-09T10:29:00" which due to a bug in the function fromObject in Types.time_point_sec in  the file
\node_modules\bitsharesjs\dist\serializer\src\types.js return 1520587740 the wrong calculted time equels "2018-03-09T09:29:00" and the hashed value will be wrong!!

This is because I live in germany and the timezone +1

The Math.floor(new Date(object).getTime() / 1000); return the wrong value because it calculate the string "2018-03-09T10:29:00" without z!

**Comment by abitmore** [comment]
So the solution should be fix `fromObject` in `Types.time_point_sec` in the file
`\node_modules\bitsharesjs\dist\serializer\src\types.js`, to always calculate as UTC time?

**Comment by hkadim** [comment]
Yes a bug fix is always good. But my workaround not relying on it.
The transactionid will be calculated correctlly.
Thanks

Am 14.03.2018 21:23 schrieb "Abit" <notifications@github.com>:

**Comment by abitmore** [comment]
@hkadim the code is
```
        if (object.getTime) return Math.floor(object.getTime() / 1000);

        if (typeof object !== "string")
            throw new Error("Unknown date type: " + object);

        if (/T[0-2][0-9]:[0-5][0-9]:[0-5][0-9]$/.test(object))
            object = object + "Z";

        return Math.floor(new Date(object).getTime() / 1000);
```
If your `object` is a string, there should be always a `Z` appended to `object`, then it should return the correct time in UTC.

However if your `object` is converted to `Date` (automatically by the engine?), it will hit the `if (object.getTime)` check then will return wrong value.

**Comment by hkadim** [comment]
thank you for your replay. I notice that have the version "bitsharesjs": "^1.4.1", and despite all, please note that the title of this issue is "example request" and I wanted to share an always working one.

**Comment by dargonar** [comment]
@hkadim @abitmore 

I know you are involved in more important things, but it would be really helpful to have a simple example of how to create raw transactions.

I'm working on a local testnet.
"bitsharesjs": "^1.7.1",

The client side gets a json signed transaction by another account. 
The tx needs to be signed by client and broadcasted.
I'm figuring out how to sign the tx and push it back to the network.

I have dive into the source code and explored several options until read this thread. 

```
var tr_x = ops.transaction.fromObject(tx);
var signed_tr_json = TransactionHelper.signed_tr_json(tr_x, [pKey]);
console.log(' TX === > ', JSON.stringify(signed_tr_json));
```
ERROR: `Error: transaction.ref_block_num	 cause: out of range 307149 uint16 307149 `

tx looks like
```
tx : {
  "expiration": "20180426T191755",
  "operations": [
    [
      7,
      {
        "account_to_list": "1.2.22",
        "authorizing_account": "1.2.18",
        "fee": {
          "amount": 300000,
          "asset_id": "1.3.0"
        },
        "new_listing": 0
      }
    ],
    [
      0,
      {
        "amount": {
          "amount": 25000,
          "asset_id": "1.3.8"
        },
        "fee": {
          "amount": 2096679,
          "asset_id": "1.3.0"
        },
        "from": "1.2.18",
        "memo": {
          "message": "7e69653a3138303432363a312e322e32323a3235303030"
        },
        "to": "1.2.22"
      }
    ],
    [
      7,
      {
        "account_to_list": "1.2.22",
        "authorizing_account": "1.2.18",
        "fee": {
          "amount": 300000,
          "asset_id": "1.3.0"
        },
        "new_listing": 2
      }
    ]
  ],
  "ref_block_num": 307149,
  "ref_block_prefix": 1342226333
}
```

Questions:
1) Should I connect to an ws to load a raw tx and sign it locally?
2) What am I doing wrong?

thanks in advance

**Comment by hkadim** [comment]
Hi,
Please provide more info:
- is this trax already Broadcasted? Why is the value ref_block_num exsist?
- how did you build it.
- the expiration value format is not the Standard. Why?
- can brovid the bolck_num and index.

Regards
Hkadim


Am 28.04.2018 15:41 schrieb "dargon" <notifications@github.com>:

@hkadim <https://github.com/hkadim> @abitmore <https://github.com/abitmore>

I know you are involved in more important things, but it would be really
helpful to have a simple example of how to create raw transactions.

I'm working on a local testnet.
"bitsharesjs": "^1.7.1",

The client side gets a json signed transaction by another account.
The tx needs to be signed by client and broadcasted.
I'm figuring out how to sign the tx and push it back to the network.

I have dive into the source code and explored several options until read
this thread.

var tr_x = ops.transaction.fromObject(tx);
var signed_tr_json = TransactionHelper.signed_tr_json(tr_x, [pKey]);
console.log(' TX === > ', JSON.stringify(signed_tr_json));

ERROR: Error: transaction.ref_block_num cause: out of range 307149 uint16
307149

tx looks like

tx : {
  "expiration": "20180426T191755",
  "operations": [
    [
      7,
      {
        "account_to_list": "1.2.22",
        "authorizing_account": "1.2.18",
        "fee": {
          "amount": 300000,
          "asset_id": "1.3.0"
        },
        "new_listing": 0
      }
    ],
    [
      0,
      {
        "amount": {
          "amount": 25000,
          "asset_id": "1.3.8"
        },
        "fee": {
          "amount": 2096679,
          "asset_id": "1.3.0"
        },
        "from": "1.2.18",
        "memo": {
          "message": "7e69653a3138303432363a312e322e32323a3235303030"
        },
        "to": "1.2.22"
      }
    ],
    [
      7,
      {
        "account_to_list": "1.2.22",
        "authorizing_account": "1.2.18",
        "fee": {
          "amount": 300000,
          "asset_id": "1.3.0"
        },
        "new_listing": 2
      }
    ]
  ],
  "ref_block_num": 307149,
  "ref_block_prefix": 1342226333
}

Questions:

   1. Should I connect to an ws to load a raw tx and sign it locally?
   2. What am I doing wrong?

thanks in advance

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bitshares/bitsharesjs/issues/9#issuecomment-385176792>,
or mute the thread
